import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { NameAndLogo } from '@/components/shared/NameAndLogo';
import { HeaderNav } from '@/components/nav/HeaderNav';
import { Footer } from '@/components/footer/Footer';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex flex-col justify-between min-h-screen'>
          <div>
            <header className='container flex flex-col sm:flex-row align-middle items-center justify-between py-6 mb-8 mx-auto main-header px-2'>
              <Link href='/'>
                <NameAndLogo />
              </Link>

              <HeaderNav />
            </header>
            <div className='px-2'>{children}</div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
